//! Config generation module for Claude Code and Cursor config snippets.
//!
//! Provides pure rendering functions that convert a `HubConfig` into
//! ready-to-paste JSON blocks for the target editor's MCP server config.
//! All rendering is offline — no daemon connection required.

use anyhow::Context as _;
use chrono::Utc;
use serde_json::{json, Value};

use crate::config::{self, HubConfig};
use crate::control::DaemonResponse;

// ─────────────────────────────────────────────────────────────────────────────
// Public types
// ─────────────────────────────────────────────────────────────────────────────

/// Per-server live state for `--live` mode comments.
///
/// Populated from a daemon Status response; used to annotate the generated
/// config with current server health and tool lists.
pub struct ServerLiveInfo {
    pub name: String,
    pub state: String,
    pub tool_names: Vec<String>,
    /// Number of MCP resources exposed by this server (extended in Plan 02).
    #[allow(dead_code)]
    pub resource_count: usize,
    /// Number of MCP prompts exposed by this server (extended in Plan 02).
    #[allow(dead_code)]
    pub prompt_count: usize,
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/// Render a Claude Code `mcpServers` JSON block from `config`.
///
/// The output starts with a `//` comment header containing the mcp-hub version
/// and an ISO 8601 timestamp, followed by a hint to paste the block into
/// `~/.claude.json` or `.mcp.json`.
///
/// If `live_info` is `Some`, per-server comment annotations are injected
/// (running state, tool names).
pub fn render_claude_config(
    config: &HubConfig,
    live_info: Option<&[ServerLiveInfo]>,
) -> anyhow::Result<String> {
    let destination_hint = "// Paste into mcpServers in ~/.claude.json or .mcp.json";
    render_config_internal(config, live_info, destination_hint)
}

/// Render a Cursor `mcpServers` JSON block from `config`.
///
/// Identical to [`render_claude_config`] except the destination hint
/// references `~/.cursor/mcp.json`.
pub fn render_cursor_config(
    config: &HubConfig,
    live_info: Option<&[ServerLiveInfo]>,
) -> anyhow::Result<String> {
    let destination_hint = "// Paste into ~/.cursor/mcp.json or .cursor/mcp.json";
    render_config_internal(config, live_info, destination_hint)
}

/// Parse a daemon `Status` response into a `Vec<ServerLiveInfo>`.
///
/// For Phase 5 Plan 01, tool names are not yet included in the daemon
/// response payload; they are left empty and will be wired in Plan 02.
pub fn parse_live_info(response: &DaemonResponse) -> anyhow::Result<Vec<ServerLiveInfo>> {
    let data = response
        .data
        .as_ref()
        .context("Daemon status response contained no data")?;

    let servers = data
        .as_array()
        .context("Daemon status data is not a JSON array")?;

    let mut result = Vec::with_capacity(servers.len());
    for entry in servers {
        let name = entry
            .get("name")
            .and_then(Value::as_str)
            .unwrap_or("")
            .to_string();
        let state = entry
            .get("state")
            .and_then(Value::as_str)
            .unwrap_or("unknown")
            .to_string();
        result.push(ServerLiveInfo {
            name,
            state,
            tool_names: Vec::new(), // extended in Plan 02
            resource_count: 0,
            prompt_count: 0,
        });
    }
    Ok(result)
}

// ─────────────────────────────────────────────────────────────────────────────
// Private helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Shared rendering logic for both Claude and Cursor output formats.
fn render_config_internal(
    config: &HubConfig,
    live_info: Option<&[ServerLiveInfo]>,
    destination_hint: &str,
) -> anyhow::Result<String> {
    let version = env!("CARGO_PKG_VERSION");
    let timestamp = iso_timestamp();

    let mut header_lines = vec![
        format!("// Generated by mcp-hub v{version} at {timestamp}"),
        destination_hint.to_string(),
    ];

    // Collect warnings for http-transport servers (excluded from output).
    let warnings = build_warnings(config);
    header_lines.extend(warnings);

    // Sort server names alphabetically for deterministic output.
    let mut names: Vec<&String> = config.servers.keys().collect();
    names.sort();

    let mut mcp_servers: serde_json::Map<String, Value> = serde_json::Map::new();

    for name in &names {
        let server = &config.servers[*name];

        // HTTP transport servers are excluded from the mcpServers block.
        if server.transport == "http" {
            continue;
        }

        let resolved_env = config::resolve_env(server)
            .with_context(|| format!("Failed to resolve env for server '{name}'"))?;

        let entry = json!({
            "command": server.command,
            "args": server.args,
            "env": resolved_env,
        });

        mcp_servers.insert((*name).clone(), entry);
    }

    let output_json = json!({ "mcpServers": Value::Object(mcp_servers) });
    let json_str = serde_json::to_string_pretty(&output_json)?;

    // Inject per-server live comments if requested.
    let json_str = if let Some(info) = live_info {
        inject_live_comments(&json_str, info)
    } else {
        json_str
    };

    let header = header_lines.join("\n");
    Ok(format!("{header}\n{json_str}\n"))
}

/// Return the current UTC time in RFC 3339 format with second precision.
///
/// Example: `2026-04-08T14:30:00Z`
fn iso_timestamp() -> String {
    Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true)
}

/// Collect `// WARNING:` lines for servers that use the `http` transport.
///
/// These lines are prepended to the output before the JSON block so the user
/// knows which servers were intentionally excluded.
fn build_warnings(config: &HubConfig) -> Vec<String> {
    let mut warnings = Vec::new();
    let mut names: Vec<&String> = config.servers.keys().collect();
    names.sort();
    for name in names {
        let server = &config.servers[name];
        if server.transport == "http" {
            warnings.push(format!(
                "// WARNING: '{name}' uses http transport -- manual URL config required"
            ));
        }
    }
    warnings
}

/// Insert `//` comment lines into `serde_json::to_string_pretty` output after
/// each server's opening `{` line.
///
/// The pretty-printed JSON from serde_json formats each top-level object key as:
/// ```text
///   "server-name": {
/// ```
/// We locate those lines and append comment lines immediately after.
fn inject_live_comments(json_str: &str, live_info: &[ServerLiveInfo]) -> String {
    if live_info.is_empty() {
        return json_str.to_string();
    }

    let mut result = String::with_capacity(json_str.len() + live_info.len() * 80);
    for line in json_str.lines() {
        result.push_str(line);
        result.push('\n');

        // Detect lines of the form `    "server-name": {`
        let trimmed = line.trim();
        if trimmed.ends_with("\": {") || trimmed.ends_with("\": {}") {
            // Extract the key name between the first pair of quotes.
            if let Some(key) = trimmed.strip_prefix('"').and_then(|s| s.split('"').next()) {
                if let Some(info) = live_info.iter().find(|i| i.name == key) {
                    // State annotation (only if not running, to avoid noise).
                    if info.state != "running" {
                        result.push_str(&format!(
                            "    // WARNING: {key} is not running (state: {})\n",
                            info.state
                        ));
                    }
                    // Tool names annotation.
                    if !info.tool_names.is_empty() {
                        let names_joined = info.tool_names.join(", ");
                        result.push_str(&format!("    // {key}: tools=[{names_joined}]\n"));
                    }
                }
            }
        }
    }
    result
}

// ─────────────────────────────────────────────────────────────────────────────
// Unit tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use std::collections::HashMap;

    use super::*;
    use crate::config::{HubConfig, HubGlobalConfig, ServerConfig};

    fn make_server(command: &str, args: Vec<&str>) -> ServerConfig {
        ServerConfig {
            command: command.to_string(),
            args: args.iter().map(|s| s.to_string()).collect(),
            env: HashMap::new(),
            env_file: None,
            transport: "stdio".to_string(),
            cwd: None,
            health_check_interval: None,
            max_retries: None,
            restart_delay: None,
        }
    }

    fn make_config(servers: Vec<(&str, ServerConfig)>) -> HubConfig {
        HubConfig {
            hub: HubGlobalConfig::default(),
            servers: servers
                .into_iter()
                .map(|(k, v)| (k.to_string(), v))
                .collect(),
        }
    }

    #[test]
    fn test_claude_format_two_servers() {
        let config = make_config(vec![
            ("alpha", make_server("npx", vec!["server-a"])),
            ("beta", make_server("node", vec!["server-b"])),
        ]);
        let output = render_claude_config(&config, None).unwrap();
        assert!(
            output.contains("\"mcpServers\""),
            "must contain mcpServers key"
        );
        assert!(output.contains("\"alpha\""), "must contain alpha server");
        assert!(output.contains("\"beta\""), "must contain beta server");
        assert!(
            output.contains("\"command\": \"npx\""),
            "must contain npx command"
        );
        assert!(
            output.contains("\"command\": \"node\""),
            "must contain node command"
        );
    }

    #[test]
    fn test_cursor_format_header() {
        let config = make_config(vec![
            ("alpha", make_server("npx", vec!["server-a"])),
            ("beta", make_server("node", vec!["server-b"])),
        ]);
        let output = render_cursor_config(&config, None).unwrap();
        assert!(
            output.contains("cursor"),
            "cursor header must mention cursor"
        );
        assert!(
            output.contains("~/.cursor/mcp.json"),
            "cursor header must mention ~/.cursor/mcp.json"
        );
    }

    #[test]
    fn test_version_comment() {
        let config = make_config(vec![("s", make_server("cmd", vec![]))]);
        let output = render_claude_config(&config, None).unwrap();
        assert!(
            output.starts_with("// Generated by mcp-hub v"),
            "output must start with version comment, got: {output}"
        );
    }

    #[test]
    fn test_timestamp_format() {
        let config = make_config(vec![("s", make_server("cmd", vec![]))]);
        let output = render_claude_config(&config, None).unwrap();
        // First line should contain an ISO 8601 timestamp with T and Z.
        let first_line = output.lines().next().unwrap();
        assert!(
            first_line.contains('T'),
            "timestamp must contain T separator"
        );
        assert!(first_line.ends_with('Z'), "timestamp must end with Z (UTC)");
    }

    #[test]
    fn test_zero_servers() {
        let config = make_config(vec![]);
        let output = render_claude_config(&config, None).unwrap();
        // The output must contain an empty mcpServers object.
        assert!(
            output.contains("\"mcpServers\": {}"),
            "zero servers must produce empty mcpServers object, got: {output}"
        );
    }

    #[test]
    fn test_alphabetical_ordering() {
        let config = make_config(vec![
            ("zulu", make_server("cmd-z", vec![])),
            ("alpha", make_server("cmd-a", vec![])),
        ]);
        let output = render_claude_config(&config, None).unwrap();
        let alpha_pos = output.find("\"alpha\"").expect("alpha must be present");
        let zulu_pos = output.find("\"zulu\"").expect("zulu must be present");
        assert!(
            alpha_pos < zulu_pos,
            "alpha must appear before zulu (alphabetical order)"
        );
    }

    #[test]
    fn test_http_transport_warning() {
        let mut http_server = make_server("http://localhost:8080", vec![]);
        http_server.transport = "http".to_string();

        let config = make_config(vec![("remote", http_server)]);
        let output = render_claude_config(&config, None).unwrap();

        assert!(
            output.contains("// WARNING:"),
            "http transport must produce a WARNING comment"
        );
        // The server name should appear in the warning but NOT as a key in mcpServers.
        assert!(
            output.contains("remote"),
            "server name must appear in warning"
        );
        // Verify "remote" does NOT appear inside the mcpServers JSON as a key.
        // The mcpServers block starts after the header comments.
        let json_start = output.find('{').unwrap();
        let json_part = &output[json_start..];
        // serde_json pretty-prints keys as `"remote":` — check it's absent.
        assert!(
            !json_part.contains("\"remote\""),
            "http server must be excluded from mcpServers JSON block"
        );
    }

    #[test]
    fn test_env_passthrough() {
        let mut server = make_server("npx", vec![]);
        server
            .env
            .insert("API_KEY".to_string(), "secret123".to_string());

        let config = make_config(vec![("myserver", server)]);
        let output = render_claude_config(&config, None).unwrap();

        assert!(
            output.contains("\"API_KEY\": \"secret123\""),
            "env vars must appear in output"
        );
    }
}
